[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"
watchPatterns = ["api/**", "data/**"]

[deploy]
healthcheckPath = "/api/v1/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
